(()=>{'use strict';const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];const reduce=matchMedia('(prefers-reduced-motion: reduce)'),mobile=matchMedia('(max-width:760px)');const film=$('#film'),play=$('#play');let userPaused=reduce.matches,visible=true;
function syncVideo(){if(!userPaused&&visible&&!document.hidden)film.play().catch(()=>{play.textContent='Play film ▷';play.setAttribute('aria-label','Play background film')});else film.pause()}
film.addEventListener('play',()=>{play.textContent='Pause film Ⅱ';play.setAttribute('aria-label','Pause background film')});film.addEventListener('pause',()=>{play.textContent='Play film ▷';play.setAttribute('aria-label','Play background film')});play.addEventListener('click',()=>{userPaused=!film.paused?true:false;syncVideo()});new IntersectionObserver(e=>{visible=e[0].isIntersecting;syncVideo()},{threshold:.05}).observe(film);document.addEventListener('visibilitychange',syncVideo);reduce.addEventListener('change',()=>{userPaused=reduce.matches;syncVideo();update()});
if(!reduce.matches){document.body.classList.add('motion');const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.15});$$('.reveal').forEach(e=>io.observe(e))}
const story=$('.story'),product=$('#product'),buttons=$$('[data-detail]');let step=-1;
function choose(n){if(n===step)return;step=n;$$('.detail').forEach((e,i)=>{e.hidden=i!==n;e.classList.toggle('active',i===n)});buttons.forEach((b,i)=>b.setAttribute('aria-pressed',String(i===n)));product.style.transform=['scale(1.04)','translateY(22%) scale(1.6)','translateY(-15%) scale(1.45)'][n];product.style.transformOrigin=['50% 60%','50% 20%','50% 75%'][n];$('#step-count').textContent='0'+(n+1)+' — 03'}
buttons.forEach((b,i)=>b.addEventListener('click',()=>{if(mobile.matches||reduce.matches)choose(i);else{const start=story.getBoundingClientRect().top+scrollY;window.scrollTo({top:start+(story.offsetHeight-innerHeight)*((i+.18)/3),behavior:'smooth'})}}));
let ticking=false;function update(){ticking=false;const y=scrollY,h=$('.hero').offsetHeight,p=Math.min(1,y/h);$('.hero-copy').style.transform=reduce.matches?'none':'translateY('+(-p*60)+'px)';$('.hero-copy').style.opacity=reduce.matches?1:Math.max(0,1-p*1.5);if(!mobile.matches&&!reduce.matches){const r=story.getBoundingClientRect();const progress=Math.max(0,Math.min(.999,-r.top/Math.max(1,story.offsetHeight-innerHeight)));choose(Math.floor(progress*3))}}
addEventListener('scroll',()=>{if(!ticking){ticking=true;requestAnimationFrame(update)}},{passive:true});addEventListener('resize',update);choose(0);update();
const dialog=$('#photo-dialog');$('#photo-open').addEventListener('click',()=>dialog.showModal());$('#photo-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});
$('#copy').addEventListener('click',async()=>{const t='AFTER DARK｜Half-body Ghost Mask keychain\nBlack and white · Grey outline · Red ball chain\n'+location.href.split('#')[0];try{await navigator.clipboard.writeText(t);$('#copy-status').textContent='Product details copied.'}catch{$('#copy-status').textContent='Half-body Ghost Mask keychain｜Black and white · Grey outline · Red ball chain (select this text to copy)'}});})();
