import { useEffect, useRef, useState } from 'react';
import { ScrollScrub } from '@/components/scroll-scrub/scroll-scrub';
import { scrollScrubScenes, scrollScrubTheme } from '@/scroll-scrub-scenes';
const focusItems = [
 {name:'鬼面輪廓',icon:'mask',text:'黑色兜帽包住白色鬼面，拉長嘅表情，一眼認得。',className:'face'},
 {name:'紅色珠鏈',icon:'chain',text:'黑白以外，留低一抹鮮明。紅色珠鏈，串起整件作品。',className:'chain'},
 {name:'層次紋理',icon:'layers',text:'靠近一點，睇見輪廓邊緣同表面一層一層嘅細節。',className:'texture'}
];
const productText='鬼面半身款鑰匙圈\n黑白鬼面主體，灰色外框，紅色珠鏈。\n產品展示圖片經視覺處理，請對照原始實拍。';
export default function App(){
 const [focus,setFocus]=useState(0); const [copyStatus,setCopyStatus]=useState(''); const [fallback,setFallback]=useState(false); const dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{let dispose=()=>{};let canceled=false; if(window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;
 Promise.all([import('lenis'),import('gsap'),import('gsap/ScrollTrigger')]).then(([{default:Lenis},{gsap},{ScrollTrigger}])=>{if(canceled)return;gsap.registerPlugin(ScrollTrigger);const lenis=new Lenis({autoRaf:false,anchors:true,smoothWheel:true,duration:0.85});const tick=(time:number)=>lenis.raf(time*1000);lenis.on('scroll',ScrollTrigger.update);gsap.ticker.add(tick);gsap.ticker.lagSmoothing(0);const ctx=gsap.context(()=>{gsap.from('.closing-word',{y:45,scrollTrigger:{trigger:'.closing',start:'top bottom',end:'bottom bottom',scrub:true}})});dispose=()=>{ctx.revert();gsap.ticker.remove(tick);lenis.destroy()};});return()=>{canceled=true;dispose()};},[]);
 async function copyProduct(){try{await navigator.clipboard.writeText(productText+'\n'+window.location.href);setCopyStatus('已複製產品資料');setFallback(false)}catch{setCopyStatus('請選取下方文字複製');setFallback(true)}}
 return <>
 <a className="skip" href="#details">跳至產品細節</a>
 <header className="masthead"><a href="#entrance" className="identity" aria-label="鬼面，回到首頁"><img src="./assets/mark.png" alt="" width="36" height="36"/><span>AFTER DARK<small>鬼面半身款</small></span></a><nav aria-label="主選單"><a href="#details">細節</a><a href="#record">產品資料</a><button onClick={()=>dialog.current?.showModal()}>實拍 ↗</button></nav></header>
 <main><ScrollScrub scenes={scrollScrubScenes} theme={scrollScrubTheme} className="ghost-journey"/>
 <section className="manifesto" aria-labelledby="manifesto-title"><div className="manifesto-rule"/><h2 id="manifesto-title">細小一件。<br/><span>存在感，唔止一點。</span></h2><p>黑白輪廓，紅色珠鏈。<br/>熟悉嘅鬼面，換成隨身嘅表情。</p></section>
 <section id="details" className="details-section" aria-labelledby="details-title"><div className={'detail-photo focus-'+focusItems[focus].className}><img src="./assets/product.webp" alt="鬼面半身款鑰匙圈，白色面具、黑色兜帽、灰色外框及紅色珠鏈" width="1200" height="1600" loading="lazy"/><span className="photo-caption">產品視覺圖</span><button className="original-trigger" onClick={()=>dialog.current?.showModal()}>對照原始實拍 <span aria-hidden="true">↗</span></button></div><div className="detail-copy"><h2 id="details-title">細節，<br/>值得靠近。</h2><p className="detail-intro">揀一個細節，慢慢睇。</p><div className="focus-controls" role="group" aria-label="選擇產品細節">{focusItems.map((item,i)=><button key={item.name} aria-pressed={focus===i} onClick={()=>setFocus(i)}><img src={'./assets/'+item.icon+'.png'} alt="" width="28" height="28"/><span>{item.name}</span><span className="focus-sign" aria-hidden="true">{focus===i?'−':'+'}</span></button>)}</div><p className="focus-description" aria-live="polite">{focusItems[focus].text}</p><p className="small-note">展示圖經背景及光線處理。實際外觀請對照原始實拍。</p></div></section>
 <section className="red-story" aria-labelledby="red-title"><div className="red-image"><img src="./assets/product.webp" alt="紅色珠鏈近距離細節" loading="lazy" width="1200" height="1600"/></div><div className="red-copy"><h2 id="red-title">一抹紅，<br/>串起日常。</h2><p>留喺黑白之間嘅小小叛逆。</p></div><span className="red-word" aria-hidden="true">A LITTLE<br/>CHARACTER.</span></section>
 <section id="record" className="record" aria-labelledby="record-title"><div className="record-heading"><p className="eyebrow">THE OBJECT</p><h2 id="record-title">鬼面半身款</h2><p>每個角度，都有自己嘅表情。</p></div><dl><div><dt>款式</dt><dd>鬼面角色 · 半身款</dd></div><div><dt>類型</dt><dd>鑰匙圈 / 掛飾</dd></div><div><dt>外觀</dt><dd>黑白主體，灰色輪廓</dd></div><div><dt>配件</dt><dd>紅色珠鏈</dd></div></dl><div className="questions"><details><summary>可以睇原始產品相嗎？</summary><p>可以。<button onClick={()=>dialog.current?.showModal()}>開啟原始實拍 ↗</button>，對照產品輪廓、珠鏈同表面細節。</p></details><details><summary>影片同實物相有咩分別？</summary><p>影片及展示圖由實拍圖片作視覺延伸，加入背景、燈光同鏡頭效果。產品實際外觀以原始實拍及實物為準。</p></details><details><summary>價錢、尺寸同購買資料呢？</summary><p>目前頁面為產品展示，售價、尺寸、材質及購買方式尚未提供。你可以先複製產品資料，向賣家查詢。</p></details></div></section>
 <section className="closing" aria-labelledby="closing-title"><h2 id="closing-title">帶住個性出場。</h2><button className="copy-action" onClick={copyProduct}><span>複製產品資料</span><span aria-hidden="true">↗</span></button><p className="copy-status" role="status">{copyStatus}</p>{fallback&&<textarea aria-label="可複製嘅產品資料" readOnly value={productText} onFocus={e=>e.currentTarget.select()}/>}<div className="closing-word" aria-hidden="true">AFTER DARK</div></section>
 </main><footer><span>鬼面半身款 / PRODUCT SHOWCASE</span><a href="#entrance">返回頂部 ↑</a></footer>
 <dialog ref={dialog} className="original-dialog" aria-labelledby="original-title" onClick={e=>{if(e.target===e.currentTarget)dialog.current?.close()}}><div className="dialog-head"><h2 id="original-title">原始實拍</h2><button autoFocus aria-label="關閉原始實拍" onClick={()=>dialog.current?.close()}>關閉 ×</button></div><img src="./assets/original.jpg" alt="用戶提供嘅原始鬼面半身款鑰匙圈照片，紫色燈光下嘅黑白主體及紅色珠鏈"/><p>保留原相光線及色調，方便對照。</p></dialog>
 </>;
}
